export let quizDict = [
  {
    chiTitle: "要更快乐",
    engTitle: "To be Happier",
    chiText: [
      "学经典和苦乐有没有吗？学经典究竟可不可以引出痛苦，可不可以得到具体的快乐关系？不是离苦得乐的途径吗？如果途径是的话，我们要花多少时间来学习教典呢？如果说是途径，为什么它是途径呢？因为痛苦如果来自颠倒的认知、源于错误的见解，那么把错误的见解颠倒过来的那就是最重要的。那么谁的语言、谁的劝说、谁的语言、谁的经典，可以让我们把心里的错误改变呢？说：「法、佛法！」法有什么样的作用？能改变我们吗？能救护我们吗？法的定义喔！我们改变吗？一定是改变苦的意思，然后把没有得到的快乐，这叫改变。救护，救护是什么？如果活得好好的，救我呀？一定是从苦的地方救走，救到乐的地方，所以这就是法的本质。",
    ],
    engText: [
      "Does studying scriptures have anything to do with the issue of suffering and happiness? Can studying scriptures really remove suffering, and attain the ultimate happiness? Is it the path to remove suffering and attain happiness? If so, how much time will we devote in studying the scriptures? If it is the way to go, then what kind of path is it? For if suffering and happiness arise from inverted perception and erroneous views, then reversing the erroneous views becomes the most important task. Then whose language, whose persuasion, whose speech, and whose scriptures can help correct our flaws within? The answer is “Dharma – Buddha’s teaching!” What function does the teaching provide? Can it change us? Can it relieve us? Dharma, by definition, is to help us change. What do we need to change? It has to be transforming suffering and to attain the promised happiness. This is known as change. Then what does “relieve” mean? If one lives happily, why do I need to be relieved? It has to be relieving one from suffering aspect to happiness aspect. This is the characteristic of Dharma. ",
    ],
    audio: "",
  },
  {
    chiTitle: "增长智慧",
    engTitle: "Increase wisdom",
    chiText: [
      "说文殊菩萨代表智慧，就是这样交代一句，实际师父在带领我们走近文殊菩萨，走近光明和智慧的代表，走进论典、走进经典、走进佛陀等菩萨伟大心；学会恭敬礼敬去这样的心、去熏陶这样的心、去学习这样的心。然后就必将结束我们在林林总总对境遇所产生的一切理非作呀意、观过啊，或者是由于误解、不听不明白。等等，所产生的人与人之间的伤害；必将由于听闻教典，让我们更清澈地了解什么是最正确的量，因为它就是智慧！ 从一颗无染的心、从一个无漏的心边显出一个量，我们会学校对这样的量、听闻这样的量，并在心中先熟悉、记住，慢慢地去比对自心、调整我们的心。 皈依敬文殊菩萨、归向智慧，避免由愚痴导致的一切痛苦因果。",
    ],
    engText: [
      "Although Manjusri Bodhisattva stands for wisdom, a simple sentence like that, but in fact, Master was guiding us to get closer to Manjusri Bodhisattva, closer to the representation of wisdom, closer to the commentaries, closer to the sutras, closer to the great minds of Buddhas and Bodhisattvas. Learning to pay homage to such a great mind respectfully, to listen closely to such a great mind, to follow such a great mind, to learn to have such a great mind. Then we would definitely end our afflictions towards various arising conditions such as improper perception, fault finding, or even hurting people due to misunderstandings or not hearing [the message] clearly, etc. Because we study the scriptures, we realize what the proper cognition is. This is what is called wisdom! From an uncontaminated and untainted mind, the proper cognition manifests itself, and we will learn to benchmark against such proper cognition, listen to it and starting from familiarizing, remembering, and then gradually comparing ourselves to it, adjusting ourselves. Taking refuge in Manjusri Bodhisattva, taking refuge in wisdom, transforming all suffering cause and effect that were generated by ignorance. ",
    ],
    audio: "",
  },
  {
    chiTitle: "更加善良",
    engTitle: "Increase compassion",
    chiText: [
      "师父非常非常强调动机，像所有的佛陀、所有的善知识们一样：做什么事，我们怀着什么样的动机？当然一定要是善良的动机，所以一定要做一个善良的人，是人，一定要做一个善良的人。那么怀着一个利他的动机，甚至能够用正确的方法利益自己，就是不要伤害自己，进而把利益自己的心，再扩展到想要帮忙很多很多人。我们扩展了内心中的慈悲，和关爱他人的这种美好的品行，所以在班里的时候，我们会觉得温馨。可能会在这一个大团队里，去营队做义工的时候，我们看到义工那种笑脸，会觉得：「你我素不相识，为什么你们会对我的生命，绽放出这样的热情呢？」很多义工感动了很多素不相识的人。那么这些义工一定是最先被感动了——被师父感动了！",
    ],
    engText: [
      "Our Master places great, great emphasis on motivation—just like all Buddhas and all virtuous teachers: whatever we do, what should our motivation be? Of course, it must be a kind motivation. So we must be kind. As human beings, we must be kind.",
      "With an altruistic motivation—even when we benefit ourselves in the right way—it means not harming ourselves, and then gradually expanding that intention of benefiting ourselves into a wish to help many, many others. We are growing the compassion and the caring heart within us, developing these beautiful qualities.",
      "That’s why, in Lamrim class, we feel warmth. And maybe in this big organization, when we go to learning camps, we see volunteers with smiling faces and we will feel: “You and I are complete strangers—why are you showing such warmth and enthusiasm toward my life?” Many volunteers have moved the hearts of many people they've never met. And these volunteers must have been the first to be touched—touched by our Master!",
    ],
    audio: "",
  },
  {
    chiTitle: "结交善友",
    engTitle: "Virtuous Friends",
    chiText: [
      "所以读圣贤书才能立什么？立志做圣贤，对不对？那现在我们是读圣贤书吧！此时此刻的你，是不是在读圣贤书？那会不会立圣贤的志向？那么圣贤的志向，一定不只是为了让自己离苦得乐的，只管自扫门前雪，那肯定当不了圣贤，一定是兼济天下的。他的认识、他的才华、他的才能，不仅仅是饶益自己而已，而且成满很多很多有情离苦得乐的愿望，去帮忙他们，跟他们做同行善友，去帮助一切，这才是圣贤的志向!",
      "那么再反过来问大家：这个志向好像很难立，但是如果有一个愿意帮忙所有的人，还有一个只愿意顾自己的人，那你愿意跟谁交朋友呢？你觉得跟谁交朋友你会比较赚呢？一定是乐于助人的那个朋友，你比较愿意交吧！因为万一到了什么为难的时刻，那个朋友一定会对你伸出援助之手，甚至他会为了你舍却自己。一定是这样的挚友最难忘吧！最可交！所以看起来我们喜欢这种人，而且我们从骨子里热爱这种人，因为这种人在生命里多好呀！到什么时候他都是我们的力量、都是我们的温暖呀",
    ],
    engText: [
      "So what is the purpose of studying noble scriptures and the classics? It is to inspire us to become the sages or saints, right? At this moment, we all are studying the noble scriptures and classics, right? Will you be inspired to become one of them? So, the aspiration of the sage is definitely not just focusing on the personal eradication of suffering and personal attaining happiness. By minding one’s own affairs, does not qualify one to be a sage; rather, the aspiration is to relieve all living beings [of their sufferings]. One’s recognition, talents, and capabilities should not only benefit oneself but also to fulfill the aspirations of many many living beings to eradicate suffering and attain happiness. Being able to help them, to be their virtuous companions and support them completely is the noble aspiration of the sage!",
      "So, let me reverse the question. This aspiration seems to be very difficult to establish. Suppose there are two persons, one is willing to help all living beings, whereas the other only cares about himself. Then who would you rather befriend? Which one you feel would be worthier to be your friend? You definitely would choose the one who is more than willing to help! In times the case of crises, this friend will for sure lend his/her helping hands, or even to the extent of sacrificing himself/herself. Such is the most unforgettable friend and the most worthy one! Hence, we not only like to befriend this type of person but we would also like them from the bottom of our hearts. How nice is it to have such a friend in our lives! Whenever needed, he/she will always offer their support and be a comfort to us!",
    ],
    audio: "",
  },
  {
    chiTitle: "健康长寿",
    engTitle: "Health & Longevity",
    chiText: [
      "薄俱罗尊者，世尊十六大弟子之一。他一生从来没生过病，从来不晓得什么叫做病，乃至于什么叫做药，也完全无法想像。为什么这样呢？世尊说，他在毗婆尸佛那个时候受了一个戒，就是五戒当中的一个戒。什么戒？不杀戒。受一个戒喔！不过不像我们马马虎虎的，他得到戒体，很认真地去持，持了这么一个戒。从此以后，九十一劫当中，他再没有生过病。不但是如此，这一生他还有一个特点——「五不死」！遭遇到非常可怕，非死不可的事情，他碰到身上都没有死。",
    ],
    engText: [
      "Venerable Bākula was one of the sixteen great disciples of the Buddha. Throughout his entire life, he never got sick—not even once. He had no idea what illness was, nor could he imagine what medicine was. Why was this the case? The Buddha explained that during the time of Vipassī Buddha, Bākula had taken a precept—one of the Five Precepts. Which one? The precept of not killing. Just a single precept! But unlike how we sometimes take precepts carelessly, he truly received the essence of the precept and practiced it with great sincerity.",
      "Because of that one precept, from that time onward for 91 kalpas, he never fell ill again. Not only that—there was another special trait in his present life: he had what was called the “five kinds of non-death.” Even when facing extremely dangerous, seemingly fatal situations, he always survived unharmed.",
    ],
    audio: "",
  },
  {
    chiTitle: "减少烦恼",
    engTitle: "Reduce afflictions",
    chiText: [
      "在广论班研讨的时候，我们都知道家家都有很难处理的问题，有的问题就是经年累月地处理不了──其实不是问题处理不了，是心里想不开呀！怎么想也想不开，所以怎么办呢？大家选择来学法，透过开发自己的智慧、开发自己的慈悲心，让自己开心之后，就会发现：其实不用特别非得让别人都做对了，自己才能够开心，不是那么被动的，是只要学到法了，只要心意开解自己就开心。而这个心意开解，不一定都依靠周围的人给你的力量，是依靠法就可以让心得到力量，自己就开解了。我们自己开心了，那不开心的人看到你开心，他也开心了。不然天天家里边愁苦着一张脸，大家都要看你的脸，这样的话都很辛苦啊！",
    ],
    engText: [
      "During our Lamrim class discussions, we all recognize that every family has problems that are hard to deal with. Some issues seem impossible to resolve even after many years—but in reality, it’s not that the problems are unsolvable; it’s that our minds are stuck. No matter how we think about it, we just can’t let it go. So what can we do? Many of us choose to study the Dharma. By developing our wisdom and compassion, we start to feel more at ease. And then we realize: we don’t have to wait for everyone else to do everything right in order for us to be happy. Happiness doesn’t have to be so passive. Once we’ve learned the Dharma and opened our hearts, joy arises from within.",
      "This kind of mental freedom doesn’t always rely on others giving us strength—it can come from the Dharma itself. The Dharma gives our hearts strength, and we become unburdened. When we feel joy, even those who are unhappy may feel uplifted just by seeing our happiness. Otherwise, if we walk around with a bitter face every day, and everyone at home has to deal with that, life becomes really hard for everyone!",
    ],
    audio: "",
  },
  {
    chiTitle: "增加福报",
    engTitle: "Increase Merits",
    chiText: [
      "不管在何年、何月、何种时代，永远孝顺父母亲、敬重父母亲，这样小孩有福报吧！对不对？小时候可能不懂事是逆子，然后慢慢长大了、懂事了，就要慢慢学会孝顺，这样就会有很大的福报，这一生就会是一个天佑之人。不是吗？这就是次第喔！教育一个人成为一个人、一个人类的特征",
    ],
    engText: [
      "No matter the year, the month, or the era, always being filial and respectful to one’s parents brings great blessings to a child—don’t you agree? As children, we may be immature and disobedient, but as we grow and become more understanding, we must gradually learn to be filial. This brings tremendous blessings and accumulates great merits. A person who practices filial piety will be someone protected by the heavens throughout their life. Isn’t that true? This is the proper progression—a step-by-step process of educating someone to become a true human being, someone who embodies the essential qualities of humanity.",
    ],
    audio: "",
  },
  {
    chiTitle: "生命意义",
    engTitle: "Meaning of life",
    chiText: [""],
    engText: [""],
    audio: "",
  },
  {
    chiTitle: "停止痛苦",
    engTitle: "Stop suffering",
    chiText: [""],
    engText: [""],
    audio: "",
  },
  {
    chiTitle: "家庭和谐",
    engTitle: "Family Harmony",
    chiText: [""],
    engText: [""],
    audio: "",
  },
  {
    chiTitle: "不堕恶趣",
    engTitle: "No lower realms",
    chiText: [""],
    engText: [""],
    audio: "",
  },
  {
    chiTitle: "脱离轮回",
    engTitle: "Break the cycle",
    chiText: [""],
    engText: [""],
    audio: "",
  },
  {
    chiTitle: "我要成佛",
    engTitle: "Attain buddhahood",
    chiText: [""],
    engText: [""],
    audio: "",
  },
  {
    chiTitle: "心力变强",
    engTitle: "Enhance mental strength",
    chiText: [""],
    engText: [""],
    audio: "",
  },
  {
    chiTitle: "佛门礼仪",
    engTitle: "Buddhist etiquette",
    chiText: [""],
    engText: [""],
    audio: "",
  },
  {
    chiTitle: "面对逆境",
    engTitle: "Learn to face adversity",
    chiText: [""],
    engText: [""],
    audio: "",
  },
];

export function populateQuizGrid(quizDict) {
  const quizGridDiv = document.getElementById("quizGridDiv");
  quizGridDiv.innerHTML = ""; // Clear existing content

  quizDict.forEach((item) => {
    const label = document.createElement("label");
    label.className = "quizGrid flex justify-between items-center gap-2";
    label.setAttribute("for", item.chiTitle);

    const input = document.createElement("input");
    input.type = "radio";
    input.className = "quizRadio";
    input.name = "quiz";
    input.id = item.chiTitle;
    input.value = item.chiTitle;

    const engSpan = document.createElement("span");
    engSpan.className =
      "text-center grow flex text-2xl items-center break-words hyphens-auto";
    engSpan.textContent = item.engTitle;

    const chiSpan = document.createElement("span");
    chiSpan.className = "text-5xl text-center";
    chiSpan.textContent = item.chiTitle;

    label.appendChild(input);
    label.appendChild(chiSpan);
    label.appendChild(engSpan);
    quizGridDiv.appendChild(label);
  });

  // reattach event listeners after dynamic rendering
  attachQuizListeners();
}

function stopAudio() {
  if (currentAudio) {
    currentAudio.pause();
    currentAudio.currentTime = 0; // Reset playback
  }
}

let lastChecked = null;
let currentAudio = null;
let backend_url = import.meta.env.VITE_BACKEND_URL || "http://localhost:5000";

function attachQuizListeners() {
  document.querySelectorAll(".quizRadio").forEach((radio) => {
    radio.addEventListener("click", function (event) {
      stopAudio();

      if (this === lastChecked) {
        this.checked = false;
        lastChecked = null;
        document.getElementById("selectionTextChi").innerText = "请选一个！";
        document.getElementById("selectionTextEng").innerText =
          "Please choose one!";
        document.querySelector("#quizRegisterBtn").classList.add("hidden");
      } else {
        lastChecked = this;
        document.getElementById("selectionTextChi").innerHTML = "";
        document.getElementById("selectionTextEng").innerHTML = "";

        const selected = quizDict.find((item) => item.chiTitle === this.value);
        for (let text of selected.chiText || []) {
          const p = document.createElement("p");
          p.textContent = text;
          document.getElementById("selectionTextChi").append(p);
        }

        for (let text of selected.engText || []) {
          const p = document.createElement("p");
          p.textContent = text;
          document.getElementById("selectionTextEng").append(p);
        }

        document.querySelector("#quizRegisterBtn").classList.remove("hidden");

        if (selected.audio) {
          fetch(`${backend_url}/stream-audio?audio=${selected.audio}`)
            .then((response) => response.blob())
            .then((blob) => {
              const url = URL.createObjectURL(blob);
              currentAudio = new Audio(url);
              currentAudio.play();
            })
            .catch((error) => console.error("Error loading audio:", error));
        }
      }
    });
  });
}
